add ignored_keys option
epsagon/epsagon-ruby pull request #42
Opened 2021-07-06 15:52 UTC by assafp

2021-07-06 21:02 UTC, schultyy commented
@assafp Thank you for this PR!
Could you add tests for this feature in the `spec/` folder?

2021-07-08 12:54 UTC, ronyis commented on README.md
> +Keys to exclude from the trace can be re-configured from code at any point after `Epsagon.init`. e.g.:
Let's add 'Advanced Configuration' section (below the table)

2021-07-08 12:56 UTC, ronyis commented on README.md
> +|ignore_domains          |EPSAGON_IGNORE_DOMAINS         |List   |newrelic.com |List of domains to be excluded from the trace
Let's add `newrelic.com` to the configuration added by the user (so the default should be a list `[]`)

2021-07-08 13:06 UTC, ronyis commented on lib/util.rb
> +  def self.prepare_attr(key, value, max_size, excluded_keys)
Make sure to add detailed tests for the logic here

2021-07-08 13:47 UTC, schultyy commented on lib/epsagon.rb
>      unless args.keys.all? {|a| MUTABLE_CONF_KEYS.include?(a)}
Why do we need to check this here?

2021-07-08 13:47 UTC, schultyy commented on lib/epsagon.rb
>      Epsagon.init unless @@initialized
Why do we need to call `Epsagon.init` again? Right now, the only method calling `set_config` is `Epsagon.init`.

2021-07-08 13:49 UTC, schultyy commented on lib/instrumentation/aws_sdk_plugin.rb
> +        attributes['aws.sqs.record.message_attributes'] = context.params[:message_attributes] if context.params[:message_attributes]
Is `context.params[:message_attributes]` already a JSON String? Or do we still need to `JSON.dump` as it used to be before?

2021-07-08 13:49 UTC, schultyy commented on lib/instrumentation/aws_sdk_plugin.rb
> +        attributes['aws.sns.message_attributes'] = context.params[:message_attributes] if context.params[:message_attributes]
same as above

2021-07-08 13:50 UTC, schultyy commented on lib/util.rb
> +  def self.prepare_attr(key, value, max_size, excluded_keys)
What does `prepare_attr` do?

2021-07-08 13:52 UTC, schultyy commented on lib/epsagon.rb
> +        v = Util.prepare_attr(k, v, Epsagon.get_config[:max_attribute_size], Epsagon.get_config[:ignored_keys])
I'm not sure if I understand what's happening here.

2021-07-09 18:41 UTC, schultyy requested changes

2021-07-09 18:41 UTC, schultyy commented on lib/epsagon.rb
> +    get_config[:ignored_keys].push(key).uniq
I noticed the `.uniq` call here. Is the intention here to `uniq` all entries in `get_config[:ignored_keys]`? If so, please change it to `.uniq!` as `.uniq` returns a new list with duplicates removed.

2021-07-09 18:41 UTC, schultyy commented on lib/epsagon.rb
> +      }.compact]
Could you add a comment that explains what `initialize` is doing at this point? From reading the code I understand that `@attributes` get sanitized, but it's not clear why we need this here.

2021-07-09 18:41 UTC, schultyy commented on lib/instrumentation/net_http.rb
> +                          'http.request.headers' => Hash[headers],
I noticed the format change here from a JSON-formatted string to a Hash. Do we need to stringify the Hash or can we send the span as is?

2021-07-09 18:41 UTC, schultyy commented on lib/instrumentation/net_http.rb
> +      span.set_attribute('http.response.headers', Hash[response.each_header.to_a])
Same as above - do we need to stringify this hash before sending?

2021-07-09 18:45 UTC, schultyy commented on lib/epsagon.rb
>      Epsagon.init unless @@initialized
Revisiting my previous comment, I'm thinking that since `set_config` is called only once from within our code, let's make it private as the user provides their config through `Epsagon.init` or environment variables.

2021-08-04 03:58 UTC, merged